### ISSUE TITLE
rectangle region support

### ISSUE THREAD

**Issue by daisychain-jp** [magnars/fold-this.el#10]
Is it possible to support rectangle region?

**Comment by Fuco1** [comment]
Yes but what should it do?

**Comment by daisychain-jp** [comment]
I have log files that have long well-formed time stamps at beginning of each line, and I want to fold time stamps.
fold-this[-xxx] commands fold unmarked strings (log messages) next to multi-line region as well.
Is there any solution?

**Comment by Fuco1** [comment]
No, this package can't do that (yet).

Best way would be to place the `invisible` text property on the text you want to hide.

**Comment by daisychain-jp** [comment]
Thanks for your advice
hide-region.el could hide region using text property but it does not support rectangle region.
I'll make my own one.
