### ISSUE TITLE
Fold doesn't fold whole region.

### ISSUE THREAD

**Issue by caoliver** [magnars/fold-this.el#16]
#'fold-this leaves the first and last characters out of the fold.  The region size tweakery in #'fold-this and #'fold-this--save-overlay-to-alist introduced in commit d1bca6b42044 are incorrect.

**Comment by PierreTechoueyres** [comment]
I'll try to find time in next weeks to work on this. And I would not call those tweaks incorrect. From my POV it's not a bug it's a feature :-) Anyway I'll work on this.

**Comment by PierreTechoueyres** [comment]
@caoliver : could you try the fix in PR #17 ?
@magnars : Could you please review it. I wouldn't add another thing you may not approve.

**Comment by magnars** [comment]
At this point you know the code much better than me, so go ahead and add
any fixes you mean improve the code.

man. 8. jul. 2019 kl. 22:57 skrev Pierre Téchoueyres <
notifications@github.com>:

**Comment by PierreTechoueyres** [comment]
@magnars : I'll wait a bit that @caoliver confirm that the PR fix the bug. But at least thank for your blessing :-) .

**Comment by caoliver** [comment]
I read the fix and understand how it works.  Could someone explain why for instance folding "while cond do things done" to "w[...]e" rather than "[[...]]" is a good thing?  I'd just have a comment external to the code or an annot.el based annotation.  Often I use fold this to remove a large swath of code so I can see what's above and below.  The "context" just looks like a mistake to me.

**Comment by caoliver** [comment]
Maybe if you show context, it should be in the fold marker string.  e.g. [[whi ... one]]]

**Comment by PierreTechoueyres** [comment]
@caoliver I've made some improvements in the PR. Does this fit better your expectations ?

And for why I find it useful to keep some text around the overlay that's because it help me track context when I abuse of them.
I think I've made this feature totally optional, so it shouldn't annoy you anymore.

**Comment by PierreTechoueyres** [comment]
@caoliver any comments ?
