### ISSUE TITLE
Any option to have better view and saving the folds? 

### ISSUE THREAD

**Issue by ReneFroger** [magnars/fold-this.el#3]
Hi Magnars, thanks for sharing this plugin! 

[Someone was hinting your plugin](http://www.reddit.com/r/emacs/comments/2xu14h/seriously_why_doesnt_emacs_support_manual_folding/w). 

I tried it out. It worked, but I have 2 wishes, if it's possible: 

- Is there any way to get the first line of the visually selected fold as the fold line? 
- Could it be possible to save the folds, for the next time that I open the same buffer, like in Vim?

**Comment by kaushalmodi** [comment]
+1

**Comment by jasonm23** [comment]
:+1: it would be a nice addition

**Comment by magnars** [comment]
Hi!

This isn't a plugin I'm using much myself, but I would be happy to accept pull requests. The code base is quite small, so it should be possible to get a handle on it quite quickly. Do let me know if you're willing to take on this task.

**Comment by ReneFroger** [comment]
Hoi Magnars, 

I would love to do so! But I'm not so experienced in Elisp yet, I need to learn it first (just using Emacs for 3 months).

**Comment by magnars** [comment]
Good luck! It's lots of fun for sure. :)

**Comment by vkazanov** [comment]
I read the post on Reddit and realized that I have some custom code for `fold-this` that gives folds the ability to survive buffer kills. I did not throw a pull request as I also wanted folds to survive *between* Emacs sessions, similar to `saveplace`.

@ReneFroger I can finalize the code the way it is (no persistence, but survive buffer kills within a single session) and create a pull request.

**Comment by ReneFroger** [comment]
@vkazanov thanks for your nice reply, that would be great :smiley:!

I have taken a look into Elisp code, to get a idea how to develop any relevant code that survives when a buffer exits. Please do a pull request, I'm curious!

**Comment by vkazanov** [comment]
@ReneFroger see the pull request #4 for the code

I will add a full-blown persistence a bit later, within a few days.

**Comment by ReneFroger** [comment]
Thanks for your reply! I checked the code, and I'm trying to figure out how this really works. 

Looks nice, it's something that I could learn a lot of from. How could I thank you?

**Comment by vkazanov** [comment]
:-D Saying "thank you" is enough. That only took 15 mins.
